/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ShellIndexRouteImport } from './routes/_shell/index'
import { Route as ShellGuestsRouteImport } from './routes/_shell/guests'
import { Route as ShellPreferencesRouteImport } from './routes/_shell/preferences'
import { Route as ShellTasksRouteImport } from './routes/_shell/tasks'
import { Route as ShellNodeRouteImport } from './routes/shell.$node'
import { Route as ShellNodeNodeRouteImport } from './routes/_shell/node.$node'
import { Route as ConsoleNodeTypeVmidRouteImport } from './routes/console.$node.$type.$vmid'
import { Route as ShellVmNodeTypeVmidRouteImport } from './routes/_shell/vm.$node.$type.$vmid'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellGuestsRoute = ShellGuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPreferencesRoute = ShellPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTasksRoute = ShellTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => ShellRoute,
} as any)
const ShellNodeRoute = ShellNodeRouteImport.update({
  id: '/shell/$node',
  path: '/shell/$node',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellNodeNodeRoute = ShellNodeNodeRouteImport.update({
  id: '/node/$node',
  path: '/node/$node',
  getParentRoute: () => ShellRoute,
} as any)
const ConsoleNodeTypeVmidRoute = ConsoleNodeTypeVmidRouteImport.update({
  id: '/console/$node/$type/$vmid',
  path: '/console/$node/$type/$vmid',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellVmNodeTypeVmidRoute = ShellVmNodeTypeVmidRouteImport.update({
  id: '/vm/$node/$type/$vmid',
  path: '/vm/$node/$type/$vmid',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/login': typeof LoginRoute
  '/guests': typeof ShellGuestsRoute
  '/preferences': typeof ShellPreferencesRoute
  '/tasks': typeof ShellTasksRoute
  '/shell/$node': typeof ShellNodeRoute
  '/node/$node': typeof ShellNodeNodeRoute
  '/console/$node/$type/$vmid': typeof ConsoleNodeTypeVmidRoute
  '/vm/$node/$type/$vmid': typeof ShellVmNodeTypeVmidRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/guests': typeof ShellGuestsRoute
  '/preferences': typeof ShellPreferencesRoute
  '/tasks': typeof ShellTasksRoute
  '/shell/$node': typeof ShellNodeRoute
  '/': typeof ShellIndexRoute
  '/node/$node': typeof ShellNodeNodeRoute
  '/console/$node/$type/$vmid': typeof ConsoleNodeTypeVmidRoute
  '/vm/$node/$type/$vmid': typeof ShellVmNodeTypeVmidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/login': typeof LoginRoute
  '/_shell/guests': typeof ShellGuestsRoute
  '/_shell/preferences': typeof ShellPreferencesRoute
  '/_shell/tasks': typeof ShellTasksRoute
  '/shell/$node': typeof ShellNodeRoute
  '/_shell/': typeof ShellIndexRoute
  '/_shell/node/$node': typeof ShellNodeNodeRoute
  '/console/$node/$type/$vmid': typeof ConsoleNodeTypeVmidRoute
  '/_shell/vm/$node/$type/$vmid': typeof ShellVmNodeTypeVmidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/guests'
    | '/preferences'
    | '/tasks'
    | '/shell/$node'
    | '/node/$node'
    | '/console/$node/$type/$vmid'
    | '/vm/$node/$type/$vmid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/guests'
    | '/preferences'
    | '/tasks'
    | '/shell/$node'
    | '/'
    | '/node/$node'
    | '/console/$node/$type/$vmid'
    | '/vm/$node/$type/$vmid'
  id:
    | '__root__'
    | '/_shell'
    | '/login'
    | '/_shell/guests'
    | '/_shell/preferences'
    | '/_shell/tasks'
    | '/shell/$node'
    | '/_shell/'
    | '/_shell/node/$node'
    | '/console/$node/$type/$vmid'
    | '/_shell/vm/$node/$type/$vmid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  LoginRoute: typeof LoginRoute
  ShellNodeRoute: typeof ShellNodeRoute
  ConsoleNodeTypeVmidRoute: typeof ConsoleNodeTypeVmidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/guests': {
      id: '/_shell/guests'
      path: '/guests'
      fullPath: '/guests'
      preLoaderRoute: typeof ShellGuestsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/preferences': {
      id: '/_shell/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof ShellPreferencesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/tasks': {
      id: '/_shell/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof ShellTasksRouteImport
      parentRoute: typeof ShellRoute
    }
    '/shell/$node': {
      id: '/shell/$node'
      path: '/shell/$node'
      fullPath: '/shell/$node'
      preLoaderRoute: typeof ShellNodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/node/$node': {
      id: '/_shell/node/$node'
      path: '/node/$node'
      fullPath: '/node/$node'
      preLoaderRoute: typeof ShellNodeNodeRouteImport
      parentRoute: typeof ShellRoute
    }
    '/console/$node/$type/$vmid': {
      id: '/console/$node/$type/$vmid'
      path: '/console/$node/$type/$vmid'
      fullPath: '/console/$node/$type/$vmid'
      preLoaderRoute: typeof ConsoleNodeTypeVmidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/vm/$node/$type/$vmid': {
      id: '/_shell/vm/$node/$type/$vmid'
      path: '/vm/$node/$type/$vmid'
      fullPath: '/vm/$node/$type/$vmid'
      preLoaderRoute: typeof ShellVmNodeTypeVmidRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellGuestsRoute: typeof ShellGuestsRoute
  ShellPreferencesRoute: typeof ShellPreferencesRoute
  ShellTasksRoute: typeof ShellTasksRoute
  ShellIndexRoute: typeof ShellIndexRoute
  ShellNodeNodeRoute: typeof ShellNodeNodeRoute
  ShellVmNodeTypeVmidRoute: typeof ShellVmNodeTypeVmidRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellGuestsRoute: ShellGuestsRoute,
  ShellPreferencesRoute: ShellPreferencesRoute,
  ShellTasksRoute: ShellTasksRoute,
  ShellIndexRoute: ShellIndexRoute,
  ShellNodeNodeRoute: ShellNodeNodeRoute,
  ShellVmNodeTypeVmidRoute: ShellVmNodeTypeVmidRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  LoginRoute: LoginRoute,
  ShellNodeRoute: ShellNodeRoute,
  ConsoleNodeTypeVmidRoute: ConsoleNodeTypeVmidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
